name:                stream-talk
version:             0.1.0.0
github:              "Skyb0rg007/stream-talk"
license:             BSD3
author:              "Skye Soss"
maintainer:          "skyler.soss@gmail.com"
copyright:           "2022 Skye Soss"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Skyb0rg007/stream-talk#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- BlockArguments
- ExistentialQuantification
- GADTs
- ImportQualifiedPost
- RankNTypes
- ScopedTypeVariables
- StandaloneKindSignatures
- TypeOperators
- UnicodeSyntax
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- TypeSynonymInstances
- FlexibleInstances
- FlexibleContexts
- LambdaCase

library:
  source-dirs: src

executables:
  stream-talk-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stream-talk

tests:
  stream-talk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stream-talk
